export const type = {
  AUTH_USER_SIGNUP_LOADING: "AUTH_USER_SIGNUP_LOADING",
  AUTH_USER_SIGNUP_SUCCESS: "AUTH_USER_SIGNUP_SUCCESS",
  AUTH_USER_SIGNUP_ERROR: "AUTH_USER_SIGNUP_ERROR",

  AUTH_USER_LOGOUT: "AUTH_USER_LOGOUT",
};
